name: Builds

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: find path
    #   run: echo ${{github.workspace}}

    - name: Install ninja-build
      run: sudo apt install ninja-build

    - name: Install llvm-11-dev
      run: sudo echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
        deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main" >> /etc/apt/sources.list.d/llvm.list && sudo apt update && sudo apt install llvm-11-dev
      # run: sudo apt install llvm-11-dev

    - name: Configure Dependencies
      shell: bash
      run: ./create_linux_build.sh

    - name: Build clang debug
      working-directory: ${{github.workspace}}/build_clang/debug
      shell: bash
      run: cmake --build .

    - name: Build clang release
      working-directory: ${{github.workspace}}/build_clang/release
      shell: bash
      run: cmake --build .

    - name: Build gcc debug
      working-directory: ${{github.workspace}}/build_gcc/debug
      shell: bash
      run: cmake --build .

    - name: Build gcc release
      working-directory: ${{github.workspace}}/build_gcc/release
      shell: bash
      run: cmake --build .
