name: Builds

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ninja-build
      run: sudo apt install ninja-build

    - name: Install llvm-10-dev
      run: sudo apt install llvm-10-dev

    - name: Configure Dependencies
      shell: bash
      run: ./create_linux_build.sh

    - name: Build clang debug
      working-directory: ${{runner.workspace}}/zodiac_new/build_clang/debug
      shell: bash
      run: cmake --build .

    - name: Build clang tracy
      working-directory: ${{runner.workspace}}/zodiac_new/build_clang/tracy
      shell: bash
      run: cmake --build .

    - name: Build gcc debug
      working-directory: ${{runner.workspace}}/zodiac_new/build_gcc/debug
      shell: bash
      run: cmake --build .
